version: '3.7'
services:
  app:
    image: app
    build: .
    ports: 
      - target: 5000
        published: 80
    depends_on:
      - mysql
mysql:
  image: mysql:5.7
  environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flaskapp
 jenkins:
   images: jenkins/jenkins: latest
   ports:
     - target: 8080
       published: 8080
    volumes:
    - type: volume
      source: jenkins-home
      target: "/var/jenkins_home"
    - type: bind
      source: "var/run/dcock
